# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sakis Kasampalis - Blog
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Occasionally writen posts about programming, free software,
  career advices, and fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sakisk.me" # the base hostname & protocol for your site
twitter_username: SKasampalis
github_username:  faif

# Build settings
markdown: kramdown
